### ISSUE TITLE
Add Wind&Rain Sensor Support

### ISSUE THREAD

**Issue by stevoboy** [ka-vaNu/ioBroker.blebox#133]
Dear all

Would it be possible to add support for the Wind&Rain Sensor?
https://blebox.eu/de/produkt/windrainsensor/

Best wishes

Steffen

**Comment by ka-vaNu** [comment]
Hi,

i'm sorry, but there is no API-Description online (https://technical.blebox.eu/). I don't have this sensor, so reverse engeneering is not an option, too.

Best wishes
Kai

**Comment by ka-vaNu** [comment]
It is possibly a [multiSensor-device](https://technical.blebox.eu/openapi_multisensor/openAPI_multiSensor_20210413.html#tag/Control-and-State/paths/~1state/get). 

@stevoboy: Could you test it? 
Please call http://IP_in_local_network/state and http://IP_in_local_network/state/extended and post the results here.

**Comment by MatthiasUlrich1** [comment]
Multisensor Schnittstelle wurde mit TempsensorAC getestet --> Funktioniert! Kann in die unterstützten Geräte aufgenommen werden.
