### ISSUE TITLE
New tempsensor v2 not recognized

### ISSUE THREAD

**Issue by garfield7791** [ka-vaNu/ioBroker.blebox#211]
Hi

There is a new tempsensor (named tempsensor_v2) which is not recognized by the adapter.
It would be very nice if this could be implemented. I am happy to help as far as i can.
For example send logs, share necessary infos, etc. Just ask what is needed.

Many thanks, with best regards
Adrian

**Comment by MatthiasUlrich1** [comment]
Hey Adrrian,

the only change of V2 is the USB C socket.
The API is the same. You can use the Tempsensor v1 integration. For the Tempsenor AC/Pro and humidity Sensor you can use the Mutisensor option.

hope that helps.

**Comment by garfield7791** [comment]
Sorry, my bad.
I forgot that i have to add it manually to the adapter. It works.
Thanks for the quick reply.

Best regards, Adrian

**Comment by MatthiasUlrich1** [comment]
Fine. 
Have Fun!
