### ISSUE TITLE
TempSensorAC elapsedTimeS bleibt auf -1, uptime wird nicht aktualisiert

### ISSUE THREAD

**Issue by ka-vaNu** [ka-vaNu/ioBroker.blebox#233]

**Comment by MatthiasUlrich1** [comment]
![Issue_elapsedTimeS](https://github.com/user-attachments/assets/ab45a476-46ca-4a83-a645-8bc994ac4b2d)

**Comment by MatthiasUlrich1** [comment]
![Issue_uptime](https://github.com/user-attachments/assets/98a99b6c-03ba-476a-9781-a599a8f29674)

**Comment by ka-vaNu** [comment]
response to API-call against fakebox multisensor:
`{
    "upTimeS": 171.67200016975403
}`

response to API-call against shutterbox (real-device):
`{
    "uptimeS": 3081671
}`

The capitalization differs

**Comment by ka-vaNu** [comment]
can you please call http://<ip or host>/api/device/uptime and post the response here

**Comment by MatthiasUlrich1** [comment]
{"uptimeS":76119}

**Comment by ka-vaNu** [comment]
Hier verhält sich die fakebox-API anders als die physischen Geräte. 
@MatthiasUlrich1 Ich sehe gerade, dass bei dir der Datenpunkt upTimeS lautet. Kannst bitte einmal den Datenpunkt löschen, dann sollte er korrekt neu erzeugt werden.

**Comment by ka-vaNu** [comment]
Die elapsedTimeS wird aus meiner Sicht korrekt beschrieben. "-1" ist ein gültiger Wert den die API so liefert (abrufbar mit http://(IP oder Host)/state/extended

Aus meiner Sicht liegt hier einfach kein gültiger Messerwert aufgrund von Verkabelung etc. vor.

**Comment by ka-vaNu** [comment]
API-Attribute werden nun case-insensitive gesucht. Löst das "uptimeS vs. upTimeS"-Problem
