### ISSUE TITLE
tempSensorPro not supported

### ISSUE THREAD

**Issue by Tscherno** [ka-vaNu/ioBroker.blebox#56]
Hi,

it seems that the tempSensorPro is not supported. It connects and shows basic information about the device, but the sensors are not loaded. It shows one without values.

**Comment by ka-vaNu** [comment]
Hi, there is no API available online and I don't have any hardware available, so unfortunately I can't help here at the moment. Maybe you can call http://<host>/state and http://<host>/state/extended and post the result here.

**Comment by MatthiasUlrich84** [comment]
Hi Kai, I will ask the manufacturer about more API information. I will come back with further information. 

Matthias
